version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: presidio
      POSTGRES_PASSWORD: presidio123
      POSTGRES_DB: ElearnDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elearnapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ElearnDb;Username=presidio;Password=presidio123

volumes:
  postgres_data:
